#!/bin/sh
#
# This pre-commit hook looks for `fdescribe`, `fit`, debugger in the
# staged files and exits with an error code of 1 if there are such changes.
#
# copied from https://gist.github.com/DerLobi/d938ac7dc422145f85e6

STATUS=0

DESCRIBEFILES=$(git diff --staged -G"^\s*fdescribe\(" --name-only | wc -l)
if [ $DESCRIBEFILES -gt 0 ]
then
  echo "You forgot to remove a fdescribe in the following files:"
  git diff --staged --name-only -G"^\s*fdescribe\("
  echo ""
  STATUS=1
fi


ITFILES=$(git diff --staged -G"^\s*fit\(" --name-only | wc -l)
if [ $ITFILES -gt 0 ]
then
  echo "You forgot to remove a fit in the following files:"
	git diff --staged --name-only -G"^\s*fit\("
  echo ""
  STATUS=1
fi

DEBUGGERFILES=$(git diff --staged -G"^\s*debugger" --name-only | wc -l)
if [ $DEBUGGERFILES -gt 0 ]
then
  echo "You forgot to remove a debugger in the following files:"
  git diff --staged --name-only -G"^\s*debugger"
  echo ""
  STATUS=1
fi

exit $STATUS
